[package]
name = "naivolt-auth"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
naivolt-core = { path = "../core" }

jsonwebtoken = "9"
argon2 = "0.5"
subtle = "2"
rand.workspace = true
getrandom.workspace = true
sha2.workspace = true
hex.workspace = true
uuid.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
rust_decimal.workspace = true

[dev-dependencies]
rust_decimal_macros.workspace = true
