[package]
name = "naivolt-ledger"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
naivolt-core = { path = "../core" }

sqlx.workspace = true
rust_decimal.workspace = true
uuid.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
tokio.workspace = true
rust_decimal_macros.workspace = true
